version: '3'

volumes:
  db-data:

services:
  app:
    container_name: better_together-app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/better_together
    ports:
      - "3000:3000"
    depends_on:
      - db
      - bundler
  db:
    container_name: better_together-db
    image: mdillon/postgis:latest
    volumes:
      - db-data:/var/lib/postgresql/data
  bundler:
    container_name: better_together-bundler
    image: busybox
    volumes:
      - .:/bundler
