default: &default
  url: <%= ENV["REDIS_URL"] || 'redis://localhost:6379' %>

development:
  <<: *default
  verbose: true
  queues:
    - [default, 1]   # Default queue with priority 1
    - [mailers, 2]   # Mailers queue with priority 2
    - [es_indexing, 3]   # Elasticsearch indexing queue with priority 3 (lower priority)
    - [geocoding, 3]   # Geocoding queue with priority 3 (lower priority)
    - [metrics, 3]   # Metrics queue with priority 3 (lower priority)

test:
  <<: *default
  queues:
    - [default, 1]   # Default queue with priority 1
    - [mailers, 2]   # Mailers queue with priority 2
    - [es_indexing, 3]   # Elasticsearch indexing queue with priority 3 (lower priority)
    - [geocoding, 3]   # Geocoding queue with priority 3 (lower priority)
    - [metrics, 3]   # Metrics queue with priority 3 (lower priority)

staging:
  <<: *default
  queues:
    - [nl_venues_staging_default, 1]   # Default queue with priority 1
    - [nl_venues_staging_mailers, 2]   # Mailers queue with priority 2
    - [nl_venues_staging_es_indexing, 3]   # Elasticsearch indexing queue with priority 3 (lower priority)
    - [nl_venues_staging_geocoding, 3]   # Geocoding queue with priority 3 (lower priority)
    - [nl_venues_staging_metrics, 3]   # Metrics queue with priority 3 (lower priority)

production:
  <<: *default
  queues:
    - [nl_venues_production_default, 1]   # Default queue with priority 1
    - [nl_venues_production_mailers, 2]   # Mailers queue with priority 2
    - [nl_venues_production_es_indexing, 3]   # Elasticsearch indexing queue with priority 3 (lower priority)
    - [nl_venues_production_geocoding, 3]   # Geocoding queue with priority 3 (lower priority)
    - [nl_venues_production_metrics, 3]   # Metrics queue with priority 3 (lower priority)