# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on: { push: { branches: [main, dev] }, pull_request: { branches: [main, dev] } }
jobs:
  rspec:
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgis/postgis:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis:7.2-alpine
        ports:
          - '6379:6379'
      elasticsearch:
        image: elasticsearch:7.17.23
        ports:
          - "9200:9200"
        env:
          "node.name": elasticsearch
          "cluster.name": nl-venues-es
          "discovery.seed_hosts": elasticsearch
          "discovery.type": single-node
          "bootstrap.memory_lock": true
          "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgis://rails:password@localhost:5432/rails_test"
      ES_HOST: "http://localhost"
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install Chrome
        run: sudo apt-get install -y chromium-browser
      - name: Generate Active Record encryption keys (test only)
        run: |
          echo "ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV
          echo "ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV
          echo "ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT=$(openssl rand -base64 32)" >> $GITHUB_ENV
      # Add or replace database setup steps here
      - name: Set up database schema
        run: rm -f tmp/pids/server.pid && bundle exec rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: rm -f tmp/pids/server.pid && bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint Ruby files with Rubocop
        run: bundle exec rubocop --parallel

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs bundler-audit --force
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
